### ISSUE TITLE
More examples.

### ISSUE THREAD

**Issue by psyciknz** [mjcumming/HomieV3#1]
Most homie implementations have a setup then a run methods.
Setup where you set up the device...  You seem to have that.

Then under run, there's a loop where it can process any events.

Is this the case?

**Comment by mjcumming** [comment]
If you use one of the predefined devices, then you do not need to call the start method. 

If you build your device then you need to call the start method.  

See https://github.com/mjcumming/Somecomfort-Homie/blob/master/homie_device/device_honeywell_thermostat.py

Is there an example that would help more?

**Comment by psyciknz** [comment]
OK, no not yet, just trying to get my head around it.  I want to add it to a pretty big project, either https://github.com/psyciknz/ParadoxIP150v2 or https://github.com/jpbarraca/pai  The latter is better suited for it I think, and with more developers that just me I could get support from them.

This is for exposing a Paradox alarm to mqtt....which means there's a bunch of potential items, etc contact (which I notice you have) for PIR sensors.  And then the alarm itself.

**Comment by mjcumming** [comment]
Got it. I'll be adding predefined devices as time allows.
