### ISSUE TITLE
Boolean properties should be lowercase

### ISSUE THREAD

**Issue by rfaelens** [mjcumming/HomieV3#10]
When using HomieV3, boolean properties are sent using string versions of python `True` or `False`. The homie convention specifies these should be the string literals `true` or `false`, see https://homieiot.github.io/specification/spec-core-v3_0_1/#boolean

For Property_Boolean, there is an easy workaround:
```
if myValue:
  property.value = "true"
else:
  property.value = "false"
```

However, the same rule should also be applied to `$settable` and `$retained`.

**Comment by mjcumming** [comment]
Agree, that is a an error - if you do a PR I'll merge the fix
